version: 2.0
jobs:
  build:
    docker:
    - image: circleci/golang:1.8
    - image: mysql:latest
      environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=circle_test
      - MYSQL_HOST=127.0.0.1
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=root

    environment:
      CIRCLE_ARTIFACTS: /tmp/artifacts
    working_directory: ~/circle-dummy-project
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS
    - run: sudo apt-get update && sudo apt-get install -y eatmydata sysbench mysql-client


    - run: ./sysbench-cpu.sh 2>&1 | tee $CIRCLE_ARTIFACTS/cpu.txt
    - run: mkdir -p io && cd io && ~/circle-dummy-project/sysbench-lio.sh 2>&1 | tee $CIRCLE_ARTIFACTS/io-localdisk.txt
    - run: mkdir -p emd && cd emd && eatmydata ~/circle-dummy-project/sysbench-lio.sh 2>&1 | tee $CIRCLE_ARTIFACTS/io-localdisk-eatmydata.txt
    - run: mkdir -p /dev/shm/sysbench && cd /dev/shm/sysbench && SIZE=3 ~/circle-dummy-project/sysbench-lio.sh 2>&1 | tee $CIRCLE_ARTIFACTS/io-shm.txt
    - run: mysql -h 127.0.0.1 -u root -e 'create database sbtest;'
    - run: MYSQL_USER=root ./sysbench-mysql.sh 2>&1 | tee $CIRCLE_ARTIFACTS/mysql.txt
    - store_artifacts:
        path: /tmp/artifacts
        destination: reports
