version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201703-01
    working_directory: /tmp

    steps:
    - run: uname -a
    - run : docker info
    - run : docker version
    - run: cat /etc/os-release
    - run: docker-compose --version
