version: 2
jobs:
  build:
    docker:
    - image: golang:1.7

    working_directory: /go/src/github.com/circleci/build-agent

    steps:
    - setup-docker-engine:
        version: 17.06.0-ce
        
    - run:
        name: Install docker 1.12
        command: |
          set -ex
          curl -L -o /tmp/docker-1.12.3.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker-1.12.3.tgz
          mv /tmp/docker/* /usr/bin

    - run : docker info
    - run : docker info
