version: 2
build_agent: picard:0.0.0-1c7c162
jobs:
  build:
    docker:
    - image: golang:1.7

    working_directory: /go/src/github.com/circleci/build-agent

    steps:
      - type: setup-docker-engine
        reusable: true
        version: 17.05.0-ce
        
      - type: shell
        name: Install docker 1.12
        command: |
          set -ex
          curl -L -o /tmp/docker-1.12.3.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker-1.12.3.tgz
          mv /tmp/docker/* /usr/bin

      - shell: docker info
