version: 2
executorType: docker
containerInfo:
  - image: golang:1.7
jobs:
  build:
    executorType: docker
    containerInfo:
      - image: golang:1.7
    workDir: /go/src/github.com/circleci/build-agent

    steps:
      - type: setup-docker-engine
        reusable: true
        
      - type: shell
        name: Install docker 1.12
        command: |
          set -ex
          curl -L -o /tmp/docker-1.12.3.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker-1.12.3.tgz
          mv /tmp/docker/* /usr/bin

      - shell: docker info
